name: iris_data
class_name: Datasource
execution_engine:
  class_name: PandasExecutionEngine

data_connectors:
  default_inferred_data_connector_name:
    class_name: InferredAssetFilesystemDataConnector
    base_directory: C:/Users/PauloOliveira/py_studies/pdcpbp_book/chapter03/great_expectations/data
    glob_directive: "*.csv"

  default_runtime_data_connector_name:   # <--- add this
    class_name: RuntimeDataConnector
    batch_identifiers:
      - default_identifier_name